---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: argo-cd
      version: "6.7.1"
      sourceRef:
        kind: HelmRepository
        name: argo-workflows
  values:
    controller:
      config:
        compute-full-forwarded-for: "true"
        use-forwarded-headers: "true"
        use-proxy-protocol: "false"
        use-gzip: "true"
      allowSnippetAnnotations: true
      kind: DaemonSet
      service:
        externalTrafficPolicy: Local
        nodePorts:
          http: 32080
          https: 32443
        type: NodePort # can be e.g. NodePort, LoadBalancer; NodePort is sufficient for a one-node demo cluster
