apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/gitops/baselayer/ingress-nginx
  prune: false
  suspend: false
  targetNamespace: ingress-nginx
