controller:
  config:
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
    use-proxy-protocol: "false"
    use-gzip: "true"
  allowSnippetAnnotations: true
  kind: DaemonSet
  service:
    externalTrafficPolicy: Local
    nodePorts:
      http: 32080
      https: 32443
    type: NodePort # can be e.g. NodePort, LoadBalancer (LB makes sense for cloud LBs only, we configure Nodes+Ports via HAproxy so NodePort is ok)
