name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      python-version: '3.12'

  build:
    needs: static-analysis
    uses: ./.github/workflows/build.yml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fastapi-image-detection:0.0.1

  push:
    needs: build
    uses: ./.github/workflows/push.yml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fastapi-image-detection:0.0.1

  scan:
    needs: push
    uses: ./.github/workflows/cve-scan.yml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fastapi-image-detection:0.0.1
