name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      python-version: '3.12'

  build-push:
    needs: static-analysis
    uses: ./.github/workflows/build-push.yml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fastapi-image-detection:0.0.1
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}

  cve-scan:
    needs: build-push
    uses: ./.github/workflows/cve-scan.yml
    with:
      image-name: ghcr.io/${{ github.repository_owner }}/fastapi-image-detection:0.0.1
