name: Build and Push Docker Image to GHCR

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
    secrets:
      GHCR_PAT:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.image-name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ inputs.image-name }}
          push: true

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
