name: Container Vulnerability Scanning

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
    secrets:
      GHCR_PAT:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ inputs.image-name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GHCR_PAT }}
