name: Push Docker Image to GHCR

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: |
          docker push ${{ inputs.image-name }}

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
